// 'use client';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MyAppBar from "@/components/sections/CommonAppBar";
import { getMenuItems } from "@/actions/Menu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sideMenuButtons = await getMenuItems();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ color: "black" }}
      >
        <MyAppBar sideMenuButtons={sideMenuButtons} />
        {/* <ThemeProvider theme={theme}>{children}</ThemeProvider> */}
        {children}
      </body>
    </html>
  );
}
